# Generated by Django 3.0.2 on 2020-01-31 09:58

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('round_time', models.TimeField(verbose_name='Round time')),
                ('pax', models.IntegerField(default=4, verbose_name='Pax')),
                ('hole', models.IntegerField(choices=[(0, '18 Holes'), (1, '9 Holes'), (2, '27 Holes'), (3, '36 Holes')], db_index=True, default=0, verbose_name='No. of holes')),
                ('green_fee_sales', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Green fee sales')),
                ('cart_fee_sales', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Cart fee sales')),
                ('caddie_fee_sales', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Caddie fee sales')),
                ('green_fee_pay_on_arrival', models.BooleanField(db_index=True, default=False, verbose_name='Green fee pay on arrival')),
                ('cart_fee_pay_on_arrival', models.BooleanField(db_index=True, default=False, verbose_name='Cart fee pay on arrival')),
                ('caddie_fee_pay_on_arrival', models.BooleanField(db_index=True, default=False, verbose_name='Caddie fee pay on arrival')),
                ('green_fee_cost', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Green fee cost')),
                ('cart_fee_cost', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Cart fee cost')),
                ('cart_fee_deducted_from_deposit', models.IntegerField(default=0, verbose_name='Cart fee deducted from deposit')),
                ('caddie_fee_cost', models.DecimalField(decimal_places=0, help_text='THB', max_digits=11, verbose_name='Caddie fee cost')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='Memo')),
                ('season', models.IntegerField(choices=[(0, 'Low season'), (1, 'High season')], db_index=True, default=1, verbose_name='High/Low Season')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Weekday'), (1, 'Weekend')], db_index=True, default=0, verbose_name='Day of week')),
                ('slot', models.IntegerField(choices=[(0, 'Morning'), (1, 'Daytime'), (2, 'Twilight'), (3, 'Night')], db_index=True, default=0, verbose_name='Time slot')),
                ('stand_by', models.BooleanField(default=False, verbose_name='Stand-by')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='DailyBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('day', models.DateField(db_index=True, unique=True, verbose_name='Booking Day')),
                ('pax', models.IntegerField(default=4, verbose_name='Pax')),
                ('green_fee_sales', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Green fee sales')),
                ('cart_fee_sales', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Cart fee sales')),
                ('caddie_fee_sales', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Caddie fee sales')),
                ('green_fee_cost', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Green fee cost')),
                ('cart_fee_cost', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Cart fee cost')),
                ('cart_fee_deducted_from_deposit', models.IntegerField(default=0, verbose_name='Cart fee deducted from deposit')),
                ('caddie_fee_cost', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Caddie fee cost')),
            ],
            options={
                'verbose_name': 'Daily booking',
                'verbose_name_plural': 'Daily bookings',
            },
        ),
        migrations.CreateModel(
            name='Golfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windmill.Booking', verbose_name='Daily booking')),
            ],
            options={
                'verbose_name': 'Golfer',
                'verbose_name_plural': 'Golfers',
            },
        ),
        migrations.CreateModel(
            name='BookingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Booking order',
                'verbose_name_plural': 'Booking orders',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='daily_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='windmill.DailyBooking', verbose_name='Daily booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='windmill.BookingOrder', verbose_name='Booking order'),
        ),
        migrations.CreateModel(
            name='TeeOffTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('hour', models.IntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(19)], verbose_name='Tee off hour')),
                ('minute', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Tee off minute')),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Held'), (2, 'Closed')], db_index=True, default=0, verbose_name='Tee off status')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windmill.DailyBooking', verbose_name='Booking day')),
            ],
            options={
                'verbose_name': 'Daily tee off time',
                'verbose_name_plural': 'Daily tee off times',
                'unique_together': {('day', 'hour', 'minute')},
            },
        ),
    ]
