# Generated by Django 3.0.2 on 2020-01-29 18:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('day', models.DateField(db_index=True, unique=True, verbose_name='Booking Day')),
            ],
            options={
                'verbose_name': 'Daily booking',
                'verbose_name_plural': 'Daily bookings',
            },
        ),
        migrations.CreateModel(
            name='TeeOffTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('hour', models.IntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(19)], verbose_name='Tee off hour')),
                ('minute', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Tee off minute')),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Held'), (2, 'Closed')], db_index=True, default=0, verbose_name='Tee off status')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windmill.DailyBooking', verbose_name='Booking day')),
            ],
            options={
                'verbose_name': 'Daily tee off time',
                'verbose_name_plural': 'Daily tee off times',
                'unique_together': {('day', 'hour', 'minute')},
            },
        ),
    ]
