# Generated by Django 3.0.2 on 2020-02-28 16:33

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoundDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('season', models.IntegerField(choices=[(0, 'Low season'), (1, 'High season')], db_index=True, default=1, verbose_name='High/Low Season')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Weekday'), (1, 'Weekend')], db_index=True, default=0, verbose_name='Day of week')),
                ('day', models.DateField(db_index=True, unique=True, verbose_name='Booking Day')),
                ('pax', models.IntegerField(default=0, verbose_name='Pax')),
            ],
            options={
                'verbose_name': 'Round day',
                'verbose_name_plural': 'Round days',
            },
        ),
        migrations.CreateModel(
            name='TeeOffTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slot', models.IntegerField(choices=[(0, 'Morning'), (1, 'Daytime'), (2, 'Twilight'), (3, 'Night')], db_index=True, default=0, verbose_name='Time slot')),
                ('type', models.IntegerField(choices=[(0, 'Fixed'), (1, 'Stand-by')], db_index=True, default=0, verbose_name='Type')),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Held'), (2, 'Sold'), (3, 'Revoked')], db_index=True, default=0, verbose_name='Status')),
                ('time', models.TimeField(verbose_name='Tee-off time')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windmill.RoundDay', verbose_name='Round day')),
            ],
            options={
                'verbose_name': 'Tee-off time',
                'verbose_name_plural': 'Tee-off times',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer name')),
                ('pax', models.IntegerField(default=4, verbose_name='Pax')),
                ('hole', models.IntegerField(choices=[(0, '18 Holes'), (1, '9 Holes'), (2, '27 Holes'), (3, '36 Holes')], db_index=True, default=0, verbose_name='No. of holes')),
                ('status', models.IntegerField(choices=[(0, 'order opened'), (1, 'order pending'), (2, 'payment pending'), (3, 'order complete'), (4, 'order offered'), (5, 'order voided'), (6, 'refund requested'), (7, 'refund pending'), (8, 'order refunded(original)'), (9, 'order refunded(reverse)')], db_index=True, default=0, verbose_name='Status')),
                ('green_fee_sales', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Green fee sales')),
                ('cart_fee_sales', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Cart fee sales')),
                ('caddie_fee_sales', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Caddie fee sales')),
                ('green_fee_pay_on_arrival', models.BooleanField(db_index=True, default=False, verbose_name='Green fee pay on arrival')),
                ('cart_fee_pay_on_arrival', models.BooleanField(db_index=True, default=False, verbose_name='Cart fee pay on arrival')),
                ('caddie_fee_pay_on_arrival', models.BooleanField(db_index=True, default=False, verbose_name='Caddie fee pay on arrival')),
                ('green_fee_cost', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Green fee cost')),
                ('cart_fee_cost', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Cart fee cost')),
                ('cart_fee_deducted_from_deposit', models.IntegerField(default=0, verbose_name='Cart fee deducted from deposit')),
                ('caddie_fee_cost', models.DecimalField(decimal_places=0, help_text='THB', max_digits=11, verbose_name='Caddie fee cost')),
                ('tee_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windmill.TeeOffTime', verbose_name='Tee-off time')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
