# Generated by Django 3.0.2 on 2020-02-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tee_off',
        ),
        migrations.AddField(
            model_name='booking',
            name='tee_off',
            field=models.ManyToManyField(to='windmill.TeeOffTime', verbose_name='Tee-off time'),
        ),
    ]
