# Generated by Django 3.0.2 on 2020-01-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='golfer',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name'),
        ),
    ]
