# Generated by Django 3.0.2 on 2020-01-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teeofftime',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Held'), (2, 'Closed')], db_index=True, default=0, verbose_name='Tee off status'),
        ),
    ]
