# Generated by Django 3.0.7 on 2020-06-15 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teeofftime',
            name='caddie_fee_cost_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caddie_fee_cost_set', to='windmill.NaoneAsset', verbose_name='Caddie fee cost asset'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='caddie_fee_sales_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caddie_fee_sales_set', to='windmill.NaoneAsset', verbose_name='Caddie fee sales asset'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='cart_fee_cost_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_fee_cost_set', to='windmill.NaoneAsset', verbose_name='Cart fee cost asset'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='cart_fee_sales_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_fee_sales_set', to='windmill.NaoneAsset', verbose_name='Cart fee sales asset'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='green_fee_cost_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='green_fee_cost_set', to='windmill.NaoneAsset', verbose_name='Green fee cost asset'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='green_fee_sales_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='green_fee_sales_set', to='windmill.NaoneAsset', verbose_name='Green fee sales asset'),
        ),
    ]
