# Generated by Django 3.0.2 on 2020-03-03 07:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='caddie_fee_cost',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='caddie_fee_pay_on_arrival',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='caddie_fee_sales',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cart_fee_cost',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cart_fee_deducted_from_deposit',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cart_fee_pay_on_arrival',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cart_fee_sales',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='green_fee_cost',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='green_fee_pay_on_arrival',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='green_fee_sales',
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='caddie_fee_cost',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Caddie fee cost'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='caddie_fee_pay_on_arrival',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Caddie fee pay on arrival'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='caddie_fee_sales',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Caddie fee sales'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='cart_fee_cost',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Cart fee cost'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='cart_fee_deducted_from_deposit',
            field=models.IntegerField(default=0, verbose_name='Cart fee deducted from deposit'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='cart_fee_pay_on_arrival',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Cart fee pay on arrival'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='cart_fee_sales',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Cart fee sales'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='green_fee_cost',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Green fee cost'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='green_fee_pay_on_arrival',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Green fee pay on arrival'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='green_fee_sales',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Green fee sales'),
        ),
    ]
