# Generated by Django 3.0.2 on 2020-01-31 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='round_date',
        ),
    ]
