# Generated by Django 3.0.2 on 2020-03-05 11:43

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='NaoneManagingBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('memo', models.CharField(max_length=255, verbose_name='Customer name')),
                ('asset_type', models.IntegerField(choices=[(0, 'Petty cash'), (1, 'Prepaid'), (2, 'Expenses'), (3, 'Green fee'), (4, 'Cart fee'), (5, 'Caddie fee')], db_index=True, default=0, verbose_name='Asset type')),
                ('cash_flow', models.IntegerField(choices=[(0, 'Cash-in'), (1, 'Cash-out')], db_index=True, default=0, verbose_name='Cash flow')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('amount', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Amount')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='windmill.Account', verbose_name='Account')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='windmill.Agency', verbose_name='Agency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
