# Generated by Django 3.0.7 on 2020-06-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naoneassettransaction',
            name='cart_fee_deducted_from_deposit',
        ),
    ]
