# Generated by Django 3.0.7 on 2020-06-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teeofftime',
            name='day',
            field=models.DateField(db_index=True, verbose_name='Round day'),
        ),
    ]
