# Generated by Django 3.0.2 on 2020-01-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybooking',
            name='day',
            field=models.DateField(db_index=True, unique=True, verbose_name='Booking Day'),
        ),
    ]
