# Generated by Django 3.0.2 on 2020-03-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0002_account_naonemanagingbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naonemanagingbook',
            options={'verbose_name': 'NA-ONE Managing Book', 'verbose_name_plural': 'NA-ONE Managing Book'},
        ),
        migrations.AddField(
            model_name='naonemanagingbook',
            name='input_type',
            field=models.IntegerField(choices=[(0, 'Manual input'), (1, 'Closing input')], db_index=True, default=0, verbose_name='Input type'),
        ),
    ]
