# Generated by Django 3.0.7 on 2020-06-15 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0002_auto_20200616_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teeofftime',
            old_name='status',
            new_name='tee_off_status',
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='windmill.Agency', verbose_name='Agency'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='booking_status',
            field=models.IntegerField(choices=[(0, 'order opened'), (1, 'order pending'), (2, 'payment pending'), (3, 'order complete'), (4, 'order offered'), (5, 'order voided'), (6, 'refund requested'), (7, 'refund pending'), (8, 'order refunded(original)'), (9, 'order refunded(reverse)')], db_index=True, default=0, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='customer_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Customer name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='hole',
            field=models.IntegerField(choices=[(0, '18 Holes'), (1, '9 Holes'), (2, '27 Holes'), (3, '36 Holes')], db_index=True, default=0, verbose_name='No. of holes'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='pax',
            field=models.IntegerField(default=4, verbose_name='Pax'),
        ),
    ]
