# Generated by Django 3.0.2 on 2020-03-05 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0002_auto_20200305_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='naonemanagingbook',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, unique=True, verbose_name='Transaction date'),
            preserve_default=False,
        ),
    ]
