# Generated by Django 3.0.2 on 2020-01-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0002_auto_20200131_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfer',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='golfer',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last name'),
        ),
    ]
