# Generated by Django 3.0.2 on 2020-03-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0002_naoneasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='naoneasset',
            name='coupon',
            field=models.BooleanField(db_index=True, default=False, verbose_name='E-Coupon'),
        ),
        migrations.AddField(
            model_name='naoneasset',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
