# Generated by Django 3.0.2 on 2020-01-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0002_auto_20200130_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='bookingorder',
            options={'verbose_name': 'Booking order', 'verbose_name_plural': 'Booking orders'},
        ),
        migrations.AlterModelOptions(
            name='golfer',
            options={'verbose_name': 'Golfer', 'verbose_name_plural': 'Golfers'},
        ),
    ]
