# Generated by Django 3.0.2 on 2020-02-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0002_auto_20200224_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='golfer',
            name='booking',
        ),
        migrations.AlterUniqueTogether(
            name='teeofftime',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='day',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingOrder',
        ),
        migrations.DeleteModel(
            name='DailyBooking',
        ),
        migrations.DeleteModel(
            name='Golfer',
        ),
        migrations.DeleteModel(
            name='TeeOffTime',
        ),
    ]
