# Generated by Django 3.0.2 on 2020-01-31 09:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0002_remove_booking_round_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybooking',
            name='caddie_fee_cost',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Caddie fee cost'),
        ),
        migrations.AddField(
            model_name='dailybooking',
            name='caddie_fee_sales',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Caddie fee sales'),
        ),
        migrations.AddField(
            model_name='dailybooking',
            name='cart_fee_cost',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Cart fee cost'),
        ),
        migrations.AddField(
            model_name='dailybooking',
            name='cart_fee_deducted_from_deposit',
            field=models.IntegerField(default=0, verbose_name='Cart fee deducted from deposit'),
        ),
        migrations.AddField(
            model_name='dailybooking',
            name='cart_fee_sales',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Cart fee sales'),
        ),
        migrations.AddField(
            model_name='dailybooking',
            name='green_fee_cost',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Green fee cost'),
        ),
        migrations.AddField(
            model_name='dailybooking',
            name='green_fee_sales',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Green fee sales'),
        ),
        migrations.AddField(
            model_name='dailybooking',
            name='pax',
            field=models.IntegerField(default=4, verbose_name='Pax'),
        ),
    ]
