# Generated by Django 3.0.7 on 2020-06-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0002_auto_20200616_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='teeofftime',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Weekday'), (1, 'Weekend')], db_index=True, default=0, verbose_name='Day of week'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='season',
            field=models.IntegerField(choices=[(0, 'Low season'), (1, 'High season')], db_index=True, default=1, verbose_name='High/Low Season'),
        ),
        migrations.AlterField(
            model_name='teeofftime',
            name='booking_status',
            field=models.IntegerField(choices=[(0, 'order opened'), (1, 'order pending'), (2, 'payment pending'), (3, 'order complete'), (4, 'order offered'), (5, 'order voided'), (6, 'refund requested'), (7, 'refund pending'), (8, 'order refunded(original)'), (9, 'order refunded(reverse)')], db_index=True, default=0, verbose_name='Booking status'),
        ),
        migrations.AlterField(
            model_name='teeofftime',
            name='tee_off_status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Held'), (2, 'Sold'), (3, 'Revoked')], db_index=True, default=0, verbose_name='Tee off status'),
        ),
        migrations.AlterField(
            model_name='teeofftime',
            name='type',
            field=models.IntegerField(choices=[(0, 'Fixed'), (1, 'Stand-by')], db_index=True, default=0, verbose_name='Tee off type'),
        ),
    ]
