# Generated by Django 3.0.2 on 2020-02-28 18:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0002_auto_20200229_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundday',
            name='cart_fee_deducted_from_deposit',
            field=models.IntegerField(default=0, verbose_name='Cart fee deducted from deposit'),
        ),
        migrations.AddField(
            model_name='roundday',
            name='cost',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Daily cost'),
        ),
        migrations.AddField(
            model_name='roundday',
            name='sales',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Daily sales'),
        ),
    ]
