# Generated by Django 3.0.2 on 2020-03-03 08:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0002_auto_20200303_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='teeofftime',
            name='caddie_fee_unit_price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Caddie fee unit price'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='cart_fee_unit_price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Cart fee unit price'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='cart_pax',
            field=models.IntegerField(default=4, verbose_name='Cart PAX'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='green_fee_unit_price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Green fee unit price'),
        ),
    ]
