# Generated by Django 3.0.7 on 2020-06-16 01:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0003_auto_20200616_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naoneasset',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='naoneasset',
            name='night',
        ),
        migrations.RemoveField(
            model_name='naoneasset',
            name='twilight',
        ),
        migrations.CreateModel(
            name='NaoneAssetTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fee', models.IntegerField(choices=[(0, 'Green fee'), (1, 'Caddie fee'), (2, 'Cart fee')], db_index=True, default=0, verbose_name='Fee')),
                ('cash_flow', models.IntegerField(choices=[(0, 'Cash-in'), (1, 'Cash-out')], db_index=True, default=0, verbose_name='Cash flow')),
                ('input_type', models.IntegerField(choices=[(0, 'Manual input'), (1, 'Closing input')], db_index=True, default=0, verbose_name='Input type')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Amount')),
                ('transaction_date', models.DateTimeField(verbose_name='Transaction date')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windmill.NaoneAsset', verbose_name='Asset')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='windmill.TeeOffTime', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Asset transaction',
                'verbose_name_plural': 'Asset transactions',
            },
        ),
    ]
