# Generated by Django 3.0.7 on 2020-06-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0003_auto_20200616_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='agency',
        ),
        migrations.DeleteModel(
            name='RoundDay',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
