# Generated by Django 3.0.2 on 2020-01-29 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0003_auto_20200129_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teeofftime',
            name='hour',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(19)], verbose_name='Tee off hour'),
        ),
        migrations.AlterField(
            model_name='teeofftime',
            name='minute',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Tee off minute'),
        ),
    ]
