# Generated by Django 3.0.2 on 2020-01-30 16:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0003_auto_20200130_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='caddie_fee_cost',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Caddie fee cost'),
        ),
        migrations.AddField(
            model_name='booking',
            name='caddie_fee_pay_on_arrival',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Caddie fee pay on arrival'),
        ),
        migrations.AddField(
            model_name='booking',
            name='caddie_fee_sales',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Caddie fee sales'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cart_fee_cost',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Cart fee cost'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cart_fee_deducted_from_deposit',
            field=models.IntegerField(default=0, verbose_name='Cart fee deducted from deposit'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cart_fee_pay_on_arrival',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Cart fee pay on arrival'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cart_fee_sales',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Cart fee sales'),
        ),
        migrations.AddField(
            model_name='booking',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Weekday'), (1, 'Weekend')], db_index=True, default=0, verbose_name='Day of week'),
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='booking',
            name='green_fee_cost',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Green fee cost'),
        ),
        migrations.AddField(
            model_name='booking',
            name='green_fee_pay_on_arrival',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Green fee pay on arrival'),
        ),
        migrations.AddField(
            model_name='booking',
            name='green_fee_sales',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Green fee sales'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hole',
            field=models.IntegerField(choices=[(0, '18 Holes'), (1, '9 Holes'), (2, '27 Holes'), (3, '36 Holes')], db_index=True, default=0, verbose_name='No. of holes'),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='booking',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='Memo'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pax',
            field=models.IntegerField(default=4, verbose_name='Pax'),
        ),
        migrations.AddField(
            model_name='booking',
            name='round_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Round day'),
        ),
        migrations.AddField(
            model_name='booking',
            name='round_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Round time'),
        ),
        migrations.AddField(
            model_name='booking',
            name='season',
            field=models.IntegerField(choices=[(0, 'Low season'), (1, 'High season')], db_index=True, default=1, verbose_name='High/Low Season'),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.IntegerField(choices=[(0, 'Morning'), (1, 'Daytime'), (2, 'Twilight'), (3, 'Night')], db_index=True, default=0, verbose_name='Time slot'),
        ),
        migrations.AddField(
            model_name='booking',
            name='stand_by',
            field=models.BooleanField(default=False, verbose_name='Stand-by'),
        ),
    ]
