# Generated by Django 3.0.8 on 2020-07-31 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0003_naoneassetbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='naoneassetbalance',
            name='month',
            field=models.IntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='naoneassetbalance',
            name='year',
            field=models.IntegerField(db_index=True, default=2020, validators=[django.core.validators.MinValueValidator(2020)], verbose_name='Year'),
        ),
        migrations.AlterUniqueTogether(
            name='naoneassetbalance',
            unique_together={('year', 'month', 'amount')},
        ),
        migrations.RemoveField(
            model_name='naoneassetbalance',
            name='year_month',
        ),
    ]
