# Generated by Django 3.0.2 on 2020-03-03 08:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0003_auto_20200303_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teeofftime',
            name='caddie_fee_unit_price',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='cart_fee_unit_price',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='green_fee_unit_price',
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='caddie_fee_sales_unit_price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Caddie fee sales unit price'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='cart_fee_sales_unit_price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Cart fee sales unit price'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='green_fee_sales_unit_price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Green fee sales unit price'),
        ),
    ]
