# Generated by Django 3.0.2 on 2020-03-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0003_auto_20200318_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='naoneasset',
            name='prepaid',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Prepaid'),
        ),
    ]
