# Generated by Django 3.0.2 on 2020-01-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0004_auto_20200130_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='caddie_fee_cost',
            field=models.DecimalField(decimal_places=0, help_text='THB', max_digits=11, verbose_name='Caddie fee cost'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='round_date',
            field=models.DateField(db_index=True, verbose_name='Round day'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='round_time',
            field=models.TimeField(verbose_name='Round time'),
        ),
    ]
