# Generated by Django 3.0.7 on 2020-06-16 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0004_auto_20200616_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naoneassettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='windmill.TeeOffTime', verbose_name='Tee-off'),
        ),
    ]
