# Generated by Django 3.0.2 on 2020-02-29 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0004_auto_20200229_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
    ]
