# Generated by Django 3.0.7 on 2020-06-16 02:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0004_auto_20200616_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naoneassettransaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='naoneassettransaction',
            name='cart_fee_deducted_from_deposit',
            field=models.IntegerField(default=0, verbose_name='Cart fee deducted from deposit'),
        ),
        migrations.AddField(
            model_name='naoneassettransaction',
            name='price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='naoneassettransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Unit price'),
        ),
    ]
