# Generated by Django 3.0.2 on 2020-03-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0004_naoneasset_prepaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naoneasset',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='naoneasset',
            name='prepaid',
        ),
        migrations.AddField(
            model_name='naoneasset',
            name='asset_type',
            field=models.IntegerField(choices=[(0, 'Petty cash'), (1, 'Prepaid'), (2, 'Bank account'), (3, 'E-Coupon')], db_index=True, default=0, verbose_name='Asset type'),
        ),
    ]
