# Generated by Django 3.0.2 on 2020-03-03 08:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0004_auto_20200303_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='teeofftime',
            name='caddie_fee_cost_unit_price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Caddie fee cost unit price'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='cart_fee_cost_unit_price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Cart fee cost unit price'),
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='green_fee_cost_unit_price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Green fee cost unit price'),
        ),
    ]
