# Generated by Django 3.0.2 on 2020-02-29 03:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0005_auto_20200229_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='weekend_afternoon',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Weekend afternoon'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='weekend_morning',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Weekend morning'),
        ),
    ]
