# Generated by Django 3.0.7 on 2020-06-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0005_auto_20200616_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naoneassettransaction',
            name='fee',
            field=models.IntegerField(choices=[(0, 'Green fee'), (1, 'Caddie fee'), (2, 'Cart fee'), (3, 'Promotion')], db_index=True, default=0, verbose_name='Fee'),
        ),
    ]
