# Generated by Django 3.0.2 on 2020-03-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0005_auto_20200305_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naonemanagingbook',
            name='asset_type',
            field=models.IntegerField(choices=[(0, 'Petty cash'), (1, 'Prepaid'), (2, 'E-Coupon')], db_index=True, default=0, verbose_name='Asset type'),
        ),
    ]
