# Generated by Django 3.0.2 on 2020-03-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0005_auto_20200318_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naoneasset',
            name='quantity',
        ),
        migrations.AddField(
            model_name='naoneasset',
            name='cart',
            field=models.IntegerField(default=0, verbose_name='Golf cart'),
        ),
        migrations.AddField(
            model_name='naoneasset',
            name='night',
            field=models.IntegerField(default=0, verbose_name='Night golf'),
        ),
        migrations.AddField(
            model_name='naoneasset',
            name='twilight',
            field=models.IntegerField(default=0, verbose_name='Twilight golf'),
        ),
    ]
