# Generated by Django 3.0.7 on 2020-06-16 02:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0005_auto_20200616_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naoneassettransaction',
            name='price',
        ),
        migrations.AddField(
            model_name='naoneassettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='THB', max_digits=11, verbose_name='Amount'),
        ),
    ]
