# Generated by Django 3.0.7 on 2020-06-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0006_auto_20200616_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teeofftime',
            name='caddie_fee_cost',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='caddie_fee_cost_asset',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='caddie_fee_cost_unit_price',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='caddie_fee_pay_on_arrival',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='caddie_fee_sales',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='caddie_fee_sales_asset',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='caddie_fee_sales_unit_price',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='cart_fee_cost',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='cart_fee_cost_asset',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='cart_fee_cost_unit_price',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='cart_fee_deducted_from_deposit',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='cart_fee_pay_on_arrival',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='cart_fee_sales',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='cart_fee_sales_asset',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='cart_fee_sales_unit_price',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='cart_pax',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='green_fee_cost',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='green_fee_cost_asset',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='green_fee_cost_unit_price',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='green_fee_pay_on_arrival',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='green_fee_sales',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='green_fee_sales_asset',
        ),
        migrations.RemoveField(
            model_name='teeofftime',
            name='green_fee_sales_unit_price',
        ),
    ]
