# Generated by Django 3.0.2 on 2020-03-02 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0006_auto_20200229_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tee_off',
        ),
        migrations.AddField(
            model_name='teeofftime',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='windmill.Booking', verbose_name='Booking'),
        ),
    ]
