# Generated by Django 3.0.7 on 2020-06-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windmill', '0007_auto_20200616_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundday',
            name='cart_fee_deducted_from_deposit',
        ),
    ]
